### ISSUE TITLE
ClubMatchResultコンポーネントの作成

### ISSUE THREAD

**Issue by ToshihiroAsami** [ToshihiroAsami/footlog-frontend#4]
マイページ上にそのユーザーの対戦相手別戦績のコンポーネントを表示する。
そのユーザーが対戦したことのあるチームの戦績のみを表示する。

このコンポーネントは対戦相手ごとの戦績を記載した子コンポーネントを並べたものからなる。

子コンポーネントの内容は以下の通り。

・対戦相手の名前
・勝ち、負け、引き分けの数
・勝率
・エンブレム(権利的に本物は無理なので、Googleが多くのJ2クラブに使用しているようなものを作成し、名前の横に表示する。)

さらに、子コンポーネントをクリックすると詳細な戦績がモーダルで表示される。
具体的には以下の通り。

・上記4つ
・ホーム、アウェイの戦績
・不敗率

＝＝＝

将来的には以下の要素も盛り込んでいきたい。
・公式の戦績との比較
	公式に比べて勝率が高ければ勝率の文字色を緑色、低ければ赤色にする。
・詳細モーダルの中に、当該チームとの対戦試合のPost一覧を表示する。

**Comment by keensyo** [comment]
@ToshihiroAsami
画面イメージを簡単に作ってみた。
こんな感じかな？
![ClubMatchResult_ToBeIdea](https://user-images.githubusercontent.com/28209852/129057380-08970b7a-adc4-4d3c-9633-f96758113310.png)
https://www.figma.com/file/f481VmkkgctH1iyg0vocyu/ClubMatchResult

ちなみに、以下が気になってる。
>そのユーザーが対戦したことのあるチームの戦績のみを表示する。

これは記録が多ければ多いほどかなりの数を画面に表示しないといけなくなるけど、どういったかたちを想定してる？
個人的には、キャプチャのようにデフォルトでいくつか表示させて残りは横スクロールで確認できるようにしたらいいかなと思った（どうやってつくるかはわからん…笑）。

>不敗率

これの計算は↓で合ってる？
不敗率 = （勝利数 + 引き分け数） /  試合数

**Comment by ToshihiroAsami** [comment]
@keensyo 
ありがとう！すごくいいと思う！！

もしよかったら、描いてくれたものをほぼそのまま作成お願いします！

カテゴリや大会のプルダウンの反映だけ、他に比べるといろいろ面倒だと予想されるのでこれは一旦省略でもいいと思う。

もともとは↓のような形でやってた。
![clubmatchresult_old](https://user-images.githubusercontent.com/43372813/129471547-2af06c19-2160-4571-89b1-fdf6fd003c44.jpeg)

> これは記録が多ければ多いほどかなりの数を画面に表示しないといけなくなる

確かにこのとおりなんだけど、それはそれで壮観で面白いかなっていう気持ちはある。
とはいえ、今のところスマホからの利用をメインと想定していて、そうすると旧リポジトリの方は流石にくどくなってしまうと思うから、少なくとも一旦は描いてくれた案の方で行きたいと思う。

> これの計算は↓で合ってる？
不敗率 = （勝利数 + 引き分け数） / 試合数

合ってる！

**Comment by keensyo** [comment]
@ToshihiroAsami
>もしよかったら、描いてくれたものをほぼそのまま作成お願いします！

了解！

旧リポジトリでの表示キャプチャありがとう。
これはたしかに壮観ではある…笑
不敗率についても承知した。

**Comment by keensyo** [comment]
## メモ
- ユーザーが観戦した試合情報をチーム毎にサマリした結果を取得するAPI（No.1）
  - 対戦チーム
  - 勝利数
  - 負け数
  - 引き分け数
  - 総試合数
  - 勝率
- No.1の詳細情報を取得するAPI（No.2）
  - ホーム&アウェイを区別して集計
  - 不敗率
- No.1で取得した情報はカードで表示
- 表示したカードをクリックするとモーダルへ遷移。ここにNo.2の情報を表示。
- 画面上にすべてのカードを表示するのではなく、横スクロールで確認できるようにする（ページング）。

APIを何度も呼ばず、モーダル内の情報は画面で処理させるなど考えたい（非同期処理とか…難しそう）。
